import { useEffect } from 'react';
import { Sun, Moon, Monitor, Palette, Type } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useThemeStore } from '@/stores/themeStore';

const THEMES = [
  { id: 'light', label: 'Light', icon: Sun, preview: 'bg-white border-slate-200' },
  { id: 'system', label: 'System', icon: Monitor, preview: 'bg-gradient-to-br from-white to-slate-800 border-slate-400' },
  { id: 'dark', label: 'Dark', icon: Moon, preview: 'bg-slate-900 border-slate-700' },
] as const;

export default function StyleStudio() {
  const { theme, setTheme, initTheme } = useThemeStore();

  useEffect(() => { initTheme(); }, [initTheme]);

  return (
    <div className="space-y-8">
      <div>
        <h1 className="font-display text-3xl font-bold text-slate-900 dark:text-white">Style Studio</h1>
        <p className="mt-1 text-slate-500">Customise how your workspace looks and feels.</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2"><Palette className="h-4 w-4" /> Theme</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-3 gap-3">
            {THEMES.map((t) => (
              <button
                key={t.id}
                onClick={() => setTheme(t.id)}
                className={`group flex flex-col items-center gap-3 rounded-2xl border-2 p-4 transition-all ${theme === t.id ? 'border-indigo-600 bg-indigo-50 dark:bg-indigo-950/40' : 'border-slate-100 hover:border-slate-200 dark:border-slate-800 dark:hover:border-slate-700'}`}
              >
                <div className={`h-16 w-full rounded-xl border-2 ${t.preview}`} />
                <div className="flex items-center gap-1.5">
                  <t.icon className={`h-3.5 w-3.5 ${theme === t.id ? 'text-indigo-600' : 'text-slate-400'}`} />
                  <span className={`text-sm font-medium ${theme === t.id ? 'text-indigo-600' : 'text-slate-600 dark:text-slate-400'}`}>{t.label}</span>
                </div>
              </button>
            ))}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2"><Type className="h-4 w-4" /> Brand Voice Preview</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="rounded-2xl bg-gradient-to-br from-indigo-50 to-purple-50 p-6 dark:from-indigo-950/40 dark:to-purple-950/40">
            <p className="text-sm italic leading-relaxed text-slate-700 dark:text-slate-300">
              "When I saw the Senior Frontend Engineer opening at TechCorp, I was immediately drawn to your focus on scalable, user-centric architecture. My 8 years of experience building performant React applications at scale aligns directly with what you're looking for..."
            </p>
            <p className="mt-3 text-xs text-slate-400">Generated by AI · Tone: Professional &amp; Confident</p>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
