import type { LegalCatalogEntry } from './legal-hub-search.types.js';

/** Curated GOV.UK / ACAS / HMRC employment-law entry points (no scraping; URLs only). */
export const LEGAL_HUB_SOURCE_CATALOG: readonly LegalCatalogEntry[] = [
  {
    title: 'Holiday entitlement',
    url: 'https://www.gov.uk/holiday-entitlement-rights',
    tier: 'core',
    tags: ['holiday', 'leave', 'annual leave', 'vacation', 'time off'],
    snippet: 'Statutory paid holiday, calculating entitlement, bank holidays.',
  },
  {
    title: 'Redundancy: your rights',
    url: 'https://www.gov.uk/redundant-your-rights',
    tier: 'core',
    tags: ['redundancy', 'layoff', 'consultation', 'pay'],
    snippet: 'Notice, consultation, redundancy pay, suitable alternative employment.',
  },
  {
    title: 'Dismissal',
    url: 'https://www.gov.uk/dismissal',
    tier: 'core',
    tags: ['dismissal', 'fired', 'termination', 'unfair'],
    snippet: 'Fair reasons, procedure, unfair dismissal basics.',
  },
  {
    title: 'Probation periods',
    url: 'https://www.gov.uk/probationary-periods',
    tier: 'core',
    tags: ['probation', 'notice', 'trial'],
    snippet: 'Probationary periods and notice during probation.',
  },
  {
    title: 'Flexible working',
    url: 'https://www.gov.uk/flexible-working',
    tier: 'core',
    tags: ['remote', 'hybrid', 'flexible', 'home working'],
    snippet: 'Right to request flexible working and employer considerations.',
  },
  {
    title: 'National Minimum Wage',
    url: 'https://www.gov.uk/national-minimum-wage',
    tier: 'core',
    tags: ['wage', 'pay', 'salary', 'minimum wage', 'nmw'],
    snippet: 'Current rates, who is entitled, deductions.',
  },
  {
    title: 'Rest breaks at work',
    url: 'https://www.gov.uk/rest-breaks-work',
    tier: 'core',
    tags: ['break', 'hours', 'working time', 'rest'],
    snippet: 'Daily and weekly rest, breaks for workers.',
  },
  {
    title: 'Zero-hours contracts',
    url: 'https://www.gov.uk/zero-hours-contracts',
    tier: 'core',
    tags: ['zero hours', 'casual', 'irregular'],
    snippet: 'Exclusivity clauses, entitlement, good practice.',
  },
  {
    title: 'Raising a grievance at work',
    url: 'https://www.gov.uk/raise-grievance-at-work',
    tier: 'core',
    tags: ['grievance', 'complaint', 'harassment', 'bullying'],
    snippet: 'Steps to raise concerns formally or informally.',
  },
  {
    title: 'Whistleblowing for employees',
    url: 'https://www.gov.uk/whistleblowing',
    tier: 'optional',
    tags: ['whistleblowing', 'protected disclosure', 'reporting'],
    snippet: 'Who is protected and what counts as a qualifying disclosure.',
  },
  {
    title: 'ACAS — Discipline and grievances at work',
    url: 'https://www.acas.org.uk/discipline-and-grievances-at-work',
    tier: 'core',
    tags: ['discipline', 'grievance', 'acas', 'hearing'],
    snippet: 'ACAS code of practice on disciplinary and grievance procedures.',
  },
  {
    title: 'ACAS — Redundancy',
    url: 'https://www.acas.org.uk/redundancy',
    tier: 'core',
    tags: ['redundancy', 'acas', 'consultation'],
    snippet: 'Good practice for fair redundancy processes.',
  },
  {
    title: 'ACAS — Settlement agreements',
    url: 'https://www.acas.org.uk/settlement-agreements',
    tier: 'optional',
    tags: ['settlement', 'compromise', 'exit'],
    snippet: 'When settlement agreements are used and independent advice.',
  },
  {
    title: 'HMRC — Employment status',
    url: 'https://www.gov.uk/employment-status',
    tier: 'optional',
    tags: ['ir35', 'contractor', 'self employed', 'worker', 'employee'],
    snippet: 'Employee vs worker vs self-employed for rights and tax.',
  },
  {
    title: 'Employment Tribunal time limits',
    url: 'https://www.gov.uk/employment-tribunals',
    tier: 'optional',
    tags: ['tribunal', 'et', 'time limit', 'claim'],
    snippet: 'Starting a claim and key deadlines (verify current limits).',
  },
];
