// PDF generation using pdfkit (pure Node.js, no browser needed)
import PDFDocument from 'pdfkit';

interface CvProfile {
  fullName?: string;
  email?: string;
  phone?: string;
  summary?: string;
  skills?: string[];
  experience?: Array<{ title?: string; company?: string; startDate?: string; endDate?: string; description?: string }>;
  education?: Array<{ degree?: string; school?: string; startDate?: string; endDate?: string }>;
}

interface CoverLetterMeta {
  recipientName?: string;
  company?: string;
  role?: string;
  senderName?: string;
}

const INDIGO = '#4f46e5';
const DARK = '#0f172a';
const MUTED = '#64748b';
const LIGHT_BG = '#f8fafc';

function bufferFromStream(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}

export async function generateCvPdf(profile: CvProfile): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margins: { top: 40, bottom: 40, left: 50, right: 50 } });
  const promise = bufferFromStream(doc);

  // Header bar
  doc.rect(0, 0, doc.page.width, 90).fill(DARK);

  const name = profile.fullName ?? 'Candidate';
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(22).text(name, 50, 25, { width: 350 });

  const contact = [profile.email, profile.phone].filter(Boolean).join('  ·  ');
  if (contact) {
    doc.fillColor('#94a3b8').font('Helvetica').fontSize(10).text(contact, 50, 55);
  }

  // Indigo accent line
  doc.rect(0, 90, doc.page.width, 4).fill(INDIGO);

  let y = 108;

  // Summary
  if (profile.summary) {
    doc.fillColor(DARK).font('Helvetica-Bold').fontSize(11).text('PROFESSIONAL SUMMARY', 50, y);
    y += 16;
    doc.fillColor(DARK).font('Helvetica').fontSize(10).text(profile.summary, 50, y, { width: 495, align: 'justify' });
    y = doc.y + 12;
  }

  // Two-column layout: left = skills, right = experience
  const leftX = 50;
  const rightX = 230;
  const leftWidth = 160;
  const rightWidth = 315;
  let leftY = y;
  let rightY = y;

  // Left: Skills
  if (profile.skills?.length) {
    doc.fillColor(INDIGO).font('Helvetica-Bold').fontSize(10).text('SKILLS', leftX, leftY);
    leftY += 14;
    doc.rect(leftX, leftY - 2, leftWidth, 1).fill(INDIGO);
    leftY += 6;
    for (const skill of profile.skills.slice(0, 20)) {
      doc.fillColor(DARK).font('Helvetica').fontSize(9).text(`▪  ${skill}`, leftX, leftY, { width: leftWidth });
      leftY = doc.y + 2;
    }
    leftY += 8;
  }

  // Right: Experience
  if (profile.experience?.length) {
    doc.fillColor(INDIGO).font('Helvetica-Bold').fontSize(10).text('EXPERIENCE', rightX, rightY);
    rightY += 14;
    doc.rect(rightX, rightY - 2, rightWidth, 1).fill(INDIGO);
    rightY += 6;
    for (const exp of profile.experience.slice(0, 5)) {
      const dates = [exp.startDate, exp.endDate].filter(Boolean).join(' – ');
      doc.fillColor(DARK).font('Helvetica-Bold').fontSize(10).text(exp.title ?? '', rightX, rightY, { width: rightWidth });
      rightY = doc.y;
      doc.fillColor(MUTED).font('Helvetica').fontSize(9)
        .text(`${exp.company ?? ''}${dates ? `  ·  ${dates}` : ''}`, rightX, rightY, { width: rightWidth });
      rightY = doc.y + 2;
      if (exp.description) {
        doc.fillColor(DARK).font('Helvetica').fontSize(9).text(exp.description.slice(0, 200), rightX, rightY, { width: rightWidth });
        rightY = doc.y + 2;
      }
      rightY += 6;
    }
  }

  // Education below (wider)
  y = Math.max(leftY, rightY) + 8;
  if (profile.education?.length) {
    doc.fillColor(INDIGO).font('Helvetica-Bold').fontSize(10).text('EDUCATION', leftX, y);
    y += 14;
    doc.rect(leftX, y - 2, 495, 1).fill(INDIGO);
    y += 6;
    for (const edu of profile.education.slice(0, 3)) {
      const dates = [edu.startDate, edu.endDate].filter(Boolean).join(' – ');
      doc.fillColor(DARK).font('Helvetica-Bold').fontSize(10).text(`${edu.degree ?? ''} — ${edu.school ?? ''}`, leftX, y, { width: 495 });
      y = doc.y;
      if (dates) {
        doc.fillColor(MUTED).font('Helvetica').fontSize(9).text(dates, leftX, y);
        y = doc.y + 2;
      }
      y += 6;
    }
  }

  // Footer
  doc.rect(0, doc.page.height - 30, doc.page.width, 30).fill(LIGHT_BG);
  doc.fillColor(MUTED).font('Helvetica').fontSize(8).text(
    `Generated by MultivoHub  ·  ${new Date().toLocaleDateString('en-GB')}`,
    0, doc.page.height - 20, { align: 'center', width: doc.page.width },
  );

  doc.end();
  return promise;
}

export async function generateCoverLetterPdf(text: string, meta: CoverLetterMeta = {}): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margins: { top: 60, bottom: 60, left: 70, right: 70 } });
  const promise = bufferFromStream(doc);

  // Header accent
  doc.rect(70, 55, 4, 60).fill(INDIGO);

  const sender = meta.senderName ?? 'Candidate';
  const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });

  doc.fillColor(DARK).font('Helvetica-Bold').fontSize(16).text(sender, 85, 60);
  doc.fillColor(MUTED).font('Helvetica').fontSize(10).text(date, 85, 82);

  let y = 140;
  if (meta.company) {
    doc.fillColor(DARK).font('Helvetica').fontSize(10).text(meta.company, 70, y);
    y += 16;
  }
  if (meta.role) {
    doc.fillColor(MUTED).fontSize(10).text(`Re: Application for ${meta.role}`, 70, y);
    y += 24;
  }

  doc.rect(70, y, 455, 1).fill('#e2e8f0');
  y += 16;

  // Body text
  const paragraphs = text.split('\n\n').filter((p) => p.trim());
  for (const para of paragraphs) {
    doc.fillColor(DARK).font('Helvetica').fontSize(10.5)
      .text(para.replace(/\n/g, ' ').trim(), 70, y, { width: 455, align: 'justify', lineGap: 3 });
    y = doc.y + 14;
  }

  doc.end();
  return promise;
}
