export const FEEDBACK_RULES = `
Feedback language policy:
- Frame feedback in terms of strengthening, clarifying, sharpening, or making something more visible.
- Do not say the answer was bad, weak, poor, chaotic, or that confidence dropped.
- Do not say the user lacks confidence, cannot do something, or is not suitable.
- Start from what already provides a good base.
- Then identify one or more areas to strengthen.
- Then provide a practical next step.

Preferred phrases:
- It would be worth strengthening...
- This could come through more clearly if...
- A stronger version of this answer would...
- From the interviewer's perspective, it would help to...
- The next step would be to...
- It would help to make your role more visible here...
- This answer could sound stronger with one concrete result...

Avoid phrases:
- This was weak.
- This was bad.
- Your confidence dropped.
- You don't know how to...
- This does not work.
- This answer was chaotic.
- You are not ready for...
`;
